Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,18 +28,13 @@ jobs:
           # failed can flipped to running.  check 3 times for flip flop.
           pwd
           ls -al
-          grid run ${{github.event.inputs.grid-args}} run.py
-          export run_name=${{ inputs.run_name }}
-          echo "run_name=${run_name}" >> $GITHUB_ENV
-          echo "run_name: ${run_name}"
-          grid logs --show-build-logs ${run_name}-exp0
+          grid run ${{github.event.inputs.grid-args}} run.py | tee grid.run.log
         shell: bash
-      - uses: robert-s-lee/actions@main
-        with:
-          obj_type: run 
-          obj_id: ${{ steps.run.outputs.run_name }}
-      - run: |
-          echo "run_name: ${env.run_name}"
-          
-          grid logs --show-build-logs ${{ env.run_name }}-exp0
+         run:|
+          export run_name=$(cat grid.run.log | awk -F: '$1=/grid_name/ {print $2}' | tr -s '[:blank:]')
+          echo "run_name=${run_name}" >> $GITHUB_ENV           
+          if [[ -z "${run_name}" ]]; then
+            echo "Error: 'grid_name:[run_name]' not found in output"
+            exit 1
+          fi   
         shell: bash
